### ISSUE TITLE
In WSSE, timestamp element loses wsu namespace when signature present.

### ISSUE THREAD

**Issue by jim0020** [savonrb/akami#27]
WSSE#security_hash doesn't merge wsu namespace attribute into timestamp element when signature? == true.

**Comment by tomdunning** [comment]
I think our PR also fixes this in passing. https://github.com/savonrb/akami/pull/29

**Comment by pcai** [comment]
fixed in #29 - see https://github.com/savonrb/akami/commit/c2bd9c8bf3dae5599020f36bf2818906bfc30f4c
