### ISSUE TITLE
Is this still mantained ?

### ISSUE THREAD

**Issue by rderoldan1** [savonrb/akami#37]
Hi, I've been using this gem for a while, and I see some important PR and issues open without any response, so that makes me wonder if you are maintaining this gem. 

I'm not demanding for anything, only checking because I have some code on production relying on this amazing gem :)

**Comment by bjensen** [comment]
I dont think it is and I am in the same boat as you. Is there an alternative?

**Comment by pcai** [comment]
Thanks for your patience. There are only a few of us and we're stretched thin, but we're here. I'm doing some housekeeping now so hopefully you'll see some of the cobwebs cleared away soon
